/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_ewriter_JniTest */

#ifndef _Included_me_ewriter_JniTest
#define _Included_me_ewriter_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_ewriter_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_ewriter_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     me_ewriter_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_ewriter_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
